version: 0.2

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - echo "ENV: "
      - env
      - go get -u github.com/golang/lint/golint
  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - pwd
      - go get -t ./...
      - go test .
