version: 0.2

env:
  variables:
    SRC_DIR: /src/github.com/vinhvu1997/Jenkins-CI
    GIT_REPO: github.com/vinhvu1997/Jenkins-CI
    #S3_BUCKET:

phases: 
  install:
    commands:
      #- mkdir -p ~/.ssh
      #- cat config > ~/.ssh/config
      - pwd
      - ls
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH

      - echo Build started
      - echo "Running go tests"
      - go test 
      - echo Creating Binaries
      - mkdir -p $GOPATH/src/github.com/TrustedKeep
      - cd $GOPATH/src/github.com/TrustedKeep
      - git clone git@github.com:TrustedKeep/kmip.git
      - go get -u
      - go install
      - dep ensure
  pre_build:
    commands:
      - pwd
  post_build:
    commands:
      - echo Build completed
# artifacts:
#   files:
#     - gotests
#     #- sum
#   discard-paths: no
