version: 0.2
phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - echo "GO ENV: "
      - go env
      - echo "ENV: "
      - env
      - go get -u github.com/golang/lint/golint
  pre_build:
    commands:
      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"
      - pwd
      # Fetch all dependencies
      - go get -t ./...
      - go test .
