version: 0.2

env:
  variables:
    SRC_DIR: /src/github.com/vinhvu1997/Jenkins-CI
    GIT_REPO: github.com/vinhvu1997/Jenkins-CI
    #S3_BUCKET:

phases: 
  install:
    commands:
      - pwd
      - ls
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH

      - echo Build started
      - echo "Running go tests"
      - go test ${GIT_REPO}/gotests/
      - echo Creating Binaries
      - go install ${GIT_REPO}/gotests/
      #- go build ${GIT_REPO}/gotests/sum.go
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  pre_build:
    commands:
      - go run gotests/sum.go
      - pwd
      - ls -l
  post_build:
    commands:
      - echo Build completed
# artifacts:
#   files:
#     - gotests
#     #- sum
#   discard-paths: no
