#!/bin/bash

for var in "$@"
do
  if [[ $lastvar == "-version" ]] ; then
    export VERSION=$var
  elif [[ $lastvar == "-release" ]] ; then
    export RELEASE=$var
  fi
  lastvar=$var
done

sed -i -e 's/LETS FIND OUT./YUP IT DOES/' version_test.txt

echo Release v$RELEASE-$VERSION Description:
read DESCRIPTION

git add version_test.txt
git commit -m "updating to version v$RELEASE-$VERSION"
git tag -a "v$RELEASE-$VERSION" -m "$DESCRIPTION"
git push --tags

